server:
  port: 9001

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:8001/.well-known/jwks.json

  datasource:
    driverclassname: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

logging:
  level:
    root: warn
    org.springframework: info
