server:
  port: 9001

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:8001/.well-known/jwks.json

  datasource:
    driverclassname: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:hsql://127.0.0.1:5005/maindb
    username:
    password:

logging:
  level:
    root: info
    org.springframework: info
