server:
  port: 8077

spring:
  security:
    oauth2:
      resource:
        jwk:
          key-set-uri: https://idp.example.com/.well-known/jwks.json
      client:
        client-id: acc_service_id
        client-secret: acc_12542_$_sec

logging:
  level:
    root: warn
    org:
      springframework: warn
