POST http://localhost:8001/oauth/token
Accept: */*
Cache-Control: no-cache
Authorization: Basic Y2xpZW50X2lkOmNsaWVudF9zZWNyZXQ=
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=Admin&password=1234
###

