# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:9001/account/save
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im9hdXRoMi1zZXJ2ZXIta2lkIn0.eyJ1c2VyX25hbWUiOiJBJGRtSW4iLCJzY29wZSI6WyJ1c2VyX2luZm8iXSwiZXhwIjoxNTg2NDU4MDcyLCJ1c2VySWQiOjEsImF1dGhvcml0aWVzIjpbIlVTRVIiXSwianRpIjoiOGQ5MTc1OTgtYzgyYS00YWM1LTg5OWUtOGZmNjc2OTVmM2UxIiwiY2xpZW50X2lkIjoiY2xpZW50X2lkIn0.mkLtnMZk-8JnEe7xBG0PpS-fqwrt3_HCvqD--dFR27VgsxQGA3NwGtdQo8U4KBc1DhlAN0m3-zRb4Bzi9TMvLxkBELTLbhZGWypubQx2rX-04JZrPIDGYRwSXF_VcVJ8EKluhs_6zMcoHlODe4zoZ3iJO48kWQNr_gqPiAMiKiTK8QQC3NKzCdvK1lQi65NmknYUgXzufHf9bnJ28M57Z_cLlLlcxfficDLrd2L0SDv5Bfjfl6IbFX0ryqka0qbISVxmOvNW3V8tDp1FjB66jfE7f1i4OgGGrESVHgwq062ugXeCNH9CbjcLqGnB_sBqorYLCWzIP0JVJuTAUuVJZg

{
  "name": "account1",
  "initialBalance": 120000
}

###