# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:9001/account/list
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im9hdXRoMi1zZXJ2ZXIta2lkIn0.eyJ1c2VyX25hbWUiOiJBJGRtSW4iLCJzY29wZSI6WyJ1c2VyX2luZm8iXSwiZXhwIjoxNTg5NzI3NTkzLCJ1c2VySWQiOjEsImF1dGhvcml0aWVzIjpbIlVTRVIiXSwianRpIjoiNmE5NDYwMDgtZmRjNi00YzVlLWFlOTMtNmY0ODhkODJlYWRmIiwiY2xpZW50X2lkIjoiY2xpZW50X2lkIn0.V4uyrh5heCQYazPA8H2O8uX2ulUk1GVQDXoXiGCJWPXQunNuEHtwWa5WIhhyEA3OsWWIjtAWCXmGNkz9Jb-CAFFbYjwy6c91Q2ZdjdAwA9QeoTlgSAo2cAjYEnsDGpr94UslKHuGYm35HktX2AmZLrkfu6VdHhSJZNIpggxAKVeYkPcDWdKj8zKFhy25e2cKUmWxQKWE1tjgCp2QAo60QLwdN-DyR9WHt9lWlvcvlubxre8Jr3Ky-PP-5seGczAHOtRi7ONgMo5y64msQkuVGyuzz4xVanySW8NLi_1FGAJfJI2vcqSk0fc4usKq8SOSbeVhQPVxto52BRkNiHcDOA
###