POST http://localhost:8001/oauth/token
Accept: */*
Cache-Control: no-cache
Authorization: Basic Y2xpZW50X2lkOmNsaWVudF9zZWNyZXQ=
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token&refresh_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im9hdXRoMi1zZXJ2ZXIta2lkIn0.eyJ1c2VyX25hbWUiOiJBJGRtSW4iLCJzY29wZSI6WyJ1c2VyX2luZm8iXSwiYXRpIjoiMDZiN2VhNzQtYTNjZC00ZDAyLTg1YTUtYzY5Yjg2MWU4N2ZmIiwiZXhwIjoxNTkyNDg0NTgyLCJ1c2VySWQiOjEsImF1dGhvcml0aWVzIjpbIlVTRVIiXSwianRpIjoiY2QyOGU4NDUtOGRhMi00OGRlLTlhZjAtZjM4NTYyNDIzMTA1IiwiY2xpZW50X2lkIjoiY2xpZW50X2lkIn0.d_LIIBmPiO11Y0Oj5gDyG40ArieVQ0p255In5d7cFg8BlHiH6EEKKCBI6f_XF_NKZYOCA9l-JrDtrvXCWlddxhKJmGsEcgQP-J6P7pI813LD2dC60Vhm6dj65EFZ9pkaJg20-usRuH-mO592g19nhZ6iSNCRfAPMNYEzxTHGm4QW5gy6QdJVNwAd9_-FfKe740hB7FH4bkTcr36VZ8pBFJJcOD_GlCJpZTlT36hNC9WG0AOSLD0JQV1lb6Im67ZcLHATkZRWxKNVBzdTnItlH2T4a0jw4I_L67vTXLXEinBZjSNHLh1LmTZjVs2jdwL-K33WIb75ht2OLHE3kNedPw
###

